### ISSUE TITLE
Syntax highlighting not consensus on my local & remote env

### ISSUE THREAD

**Issue by dusty-cjh** [torchbox/wagtail-markdown#111]
### ENV
Local env:
macOS python3.9 venv

Remote env:
Ubuntu20 python3.10 venv

Related Package Version:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/45847340/205421133-8567b18e-97e8-4644-9448-0548f0e03e6a.png">

I have downloaded and installed [pygment-css](https://github.com/richleland/pygments-css), and it only works on local ENV.
Related CSS file can be accessed correctly.

### Appearance

Local Render Effect:
![image](https://user-images.githubusercontent.com/45847340/205421187-51aff542-27e9-4ae1-8603-a9a4b1895c16.png)

Remote Render Effect:
![image](https://user-images.githubusercontent.com/45847340/205421330-b0236da8-02e7-48e2-bdd9-67b9e8071cb2.png)

since local and remote rendered different HTML for the same markdown syntax:
Local:
![image](https://user-images.githubusercontent.com/45847340/205421368-e6bb2dbb-3724-4e59-a2b3-f575a062a76c.png)

Remote:
![image](https://user-images.githubusercontent.com/45847340/205421387-6a80acc5-5f73-456f-9bbf-2b9960066b0b.png)

I don't think that is an issue, but I can not find any setting option on Doc, could you help me?
thanks a lot

**Comment by zerolab** [comment]
Can you add install Pygments on you remote dev? if that works, then you need to add Pygments to your requirements file

ref: https://github.com/torchbox/wagtail-markdown#syntax-highlighting mentions it, but should probably be more explicit

The https://python-markdown.github.io/extensions/code_hilite/ Markdown extension uses it for highlighting

**Comment by dusty-cjh** [comment]
Thanks, have solved it, it is because my CDN config error, the css file wasn’t sync with remote
