### ISSUE TITLE
Create PyPI package

### ISSUE THREAD

**Issue by marctc** [torchbox/wagtail-markdown#12]
Hi, could you upload a PyPI package? I want to include this package on the next [Puput](https://github.com/APSL/puput) release.

thanks

**Comment by philippbosch** [comment]
Please?

**Comment by marctc** [comment]
I think that this package is dead. Take a look at this: https://github.com/FlipperPA/wagtailmarkdownblock.
We are going to use in Puput.

**Comment by unixwitch** [comment]
I haven't had any time to work on this and I haven't been able to find another maintainer at Torchbox; if there's a replacement that works better I suggest using that instead.

**Comment by sannykr** [comment]
Please do that if you have time.

**Comment by tm-kn** [comment]
I've put together an alpha release - https://pypi.org/project/wagtail-markdown/. Should be installable with `pip install wagtail-markdown`.
