### ISSUE TITLE
Wagtail 5 Support

### ISSUE THREAD

**Issue by fidoriel** [torchbox/wagtail-markdown#124]
markdown is not Wagtail 5 compatible, which will be released on May the 2nd. For example Wagtail Core is deprecated and removed. have a look at: `https://docs.wagtail.org/en/latest/releases/5.0.html#upgrade-considerations`

**Comment by zerolab** [comment]
This package will be Wagtail 5.0 ready on the day 5.0 is released
The latest `main` branch should already be compatible

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtail-markdown/releases/tag/v0.11.0
