### ISSUE TITLE
Wagtail 5 upgrade problems

### ISSUE THREAD

**Issue by drkoru** [torchbox/wagtail-markdown#127]
Greetings. There were errors during my upgrade to wagtail 5.0 because wagtail-markdown uses wagtail-core which is not supported any more. An update of wagtail-markdown for wagtail 5.0 would be appreciated. Thanks

**Comment by zerolab** [comment]
This doesn't give lots of useful information. e.g. what version of the package are you using?

for example https://github.com/torchbox/wagtail-markdown/releases/tag/v0.11.0 brings Wagtail 5.0 compatibility and is tested against it

**Comment by drkoru** [comment]
I've seen that dependencies.txt had 0.10. It is a bug on our end. I'll check it with 0.11. We can close it for now.
