### ISSUE TITLE
Wagtail 6.0 depreciates the WidgetWithScript hook

### ISSUE THREAD

**Issue by byhill** [torchbox/wagtail-markdown#138]
With the release of Wagtail 6.0, the use of WidgetWithScript is now [depreciated](https://docs.wagtail.org/en/latest/releases/6.0.html#deprecated-widgetwithscript-base-widget-class).

Currently, wagtail-markdown still uses it for it's MarkdownTextArea class [here](https://github.com/torchbox/wagtail-markdown/blob/5b64706d203536c4eec9352f2f9645d52e9095d6/src/wagtailmarkdown/widgets.py#L9C7-L9C23).

This caused the warning for my Wagtail project once I upgraded the wagtail version from 5.* to 6.0.
``RemovedInWagtail70Warning: The usage of `WidgetWithScript\` hook is deprecated. Use external scripts instead.``

I'm currently using version 0.11.1 of wagtail-markdown.

**Comment by twn39** [comment]
It seems that this issue has been resolved through a PR, but a new version has not been released yet.

**Comment by twn39** [comment]
I have encountered the same issue. Could the team release a new version promptly?

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtail-markdown/releases/tag/v0.12.0

`RemovedInWagtail70Warning` is a warning, which while annoying, it doesn't break anything. And you can silence specific warnings in your project quite easily - https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python#879249


I would like to point out that the "team" is a single person. So, you know, have a bit of patience. What would really help, is to either to submit a PR with a fix, or review and test any open PRs with a fix so as to speed things up.

**Comment by twn39** [comment]
@zerolab I'm very sorry if my tone came across as pushy, I didn't mean to rush you and I appreciate you developing this plugin, it has helped me a lot.

**Comment by zerolab** [comment]
Thank you @twn39
