### ISSUE TITLE
trouble with bleach

### ISSUE THREAD

**Issue by zoombear** [torchbox/wagtail-markdown#26]
I'm deploying on Heroku using python 3.6.3
but I'm getting an error:

       Collecting wagtail-markdown==0.4.1 (from -r /tmp/build_e2d694b32c1dc181c4b75586ee858300/requirements.txt (line 49))
         Could not find a version that satisfies the requirement wagtail-markdown==0.4.1 (from -r /tmp/build_e2d694b32c1dc181c4b75586ee858300/requirements.txt (line 49)) (from versions: )
       No matching distribution found for wagtail-markdown==0.4.1 (from -r /tmp/build_e2d694b32c1dc181c4b75586ee858300/requirements.txt (line 49))

when I run
`pip install wagtail-markdown && pip freeze > requirements.txt`

It downgrades my Bleach from version 2.1.1 to version 1.4.2, which breaks my html5lib.sanitizer
I tried to upgrade bleach to fix that, as shown here:
https://github.com/ckan/ckan/issues/3257

Then when requirements are installed on deployment Bleach gets downgraded automatically due to wagtail-markdown's requirements. Can we bump up the bleach requirement here?

**Comment by tm-kn** [comment]
Should be fixed in 65ce1de70d0ec26040c3532d5a2394a6d5103770. Thanks for reporting!
