### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by tm-kn** [torchbox/wagtail-markdown#28]
Add unit tests testing the current functionality.

**Comment by lhmisho** [comment]
it's really helpfull ..
but is there any way to add color for markdown portion .. ?

**Comment by jhoover4** [comment]
Is someone working on these? If not I'd be happy to create a PR of my own.

**Comment by zerolab** [comment]
Hi @jhoover4,

Thank you for offering. A PR will be highly welcome.

**Comment by jhoover4** [comment]
Just an update: I have some testing done already, hoping to have a PR ready by end of next week or so.

**Comment by zerolab** [comment]
Initial test suite added in #84
