### ISSUE TITLE
Horizontal line - hr vs <hr>

### ISSUE THREAD

**Issue by csalom** [torchbox/wagtail-markdown#32]
Hi!
Is there a reason to have the hr tag between the symbols '<' and '>' ?

https://github.com/torchbox/wagtail-markdown/blob/0c3f5ef45badedf617fdb85e40ca718d32fe6f9e/wagtailmarkdown/utils.py#L76

I've seen this [PR](https://github.com/torchbox/wagtail-markdown/pull/20) unresolved...

**Comment by csalom** [comment]
There are any news about that, @tm-kn ?

**Comment by tm-kn** [comment]
Hi. I'll try to look at this tonight!

**Comment by tm-kn** [comment]
@csalom Can you please review #33?

**Comment by csalom** [comment]
Hi,
sorry for the late response.
I think that PR #33 it's ok and can be merged.
I've add a review. It's my first one, I hope that I've submitted in the right way.

Thank you for the work :)

**Comment by tm-kn** [comment]
Sure. Will push to PyPI when I've time (during this week hopefully).

**Comment by tm-kn** [comment]
This has been released in `0.5a3`.
