### ISSUE TITLE
SimpleMDE abandoned / forked

### ISSUE THREAD

**Issue by stuaxo** [torchbox/wagtail-markdown#36]
According to this  https://github.com/sparksuite/simplemde-markdown-editor/issues/685   simplemde hasn't received fixes in 2 years.

There are a couple of forks
https://github.com/Ionaru/simplemde-markdown-editor

https://github.com/Inscryb/inscryb-markdown-editor

It's probably worth watching the situation and seeing if it revives or if one of the forks becomes successful.

**Comment by zerolab** [comment]
Fixed in #76
