### ISSUE TITLE
Markdown without the paragraph tag ?

### ISSUE THREAD

**Issue by stuaxo** [torchbox/wagtail-markdown#38]
Text from the ```|markdown``` seems to be wrapped in ```<p>``` tags, is there any way around this ?

I'm using some markdown for a single line bit of text, but the ```<p>``` needs css to workaround.

**Comment by zerolab** [comment]
Hey @stuaxo, this is a **very** late reply, sorry about that!

tl;dr this conforms to the Markdown spec. We use python-markdown. You can see how other libraries do it - https://johnmacfarlane.net/babelmark2/?text=this+is+some+text 

One sulution would be to write your own template tag that removes them given some condition (e.g. there's only one paragraph tag)

**Comment by stuaxo** [comment]
No problem !   It's been a bit of a while since I worked on a wagtail or wagtail-markdown project (I'm a short term contractor) but I things have a way of coming round again so I'm sure I'll find this answer on a future project.
