### ISSUE TITLE
RFC - page linking.

### ISSUE THREAD

**Issue by stuaxo** [torchbox/wagtail-markdown#40]
The current tag for linking pages, links by ```Title``` obviously there is the danger of clashes, is it worth making it possible to link by id or slug ?

I wonder if it's worth adding some error checking for broken links to pages in the admin interface too ?

(Obviously ideally the editor would know about the page chooser - but this might be tricky, I guess there could be something to handle pages moving / changing too, but again, a bit tricky)

**Comment by stuaxo** [comment]
These look sensible.

I don't know how many users there are of wagtail-markdown, the only thing I'd change is make slug: the default, but obviously this would break compatibility.

All in all, this looks sensible, so +1 x 100 :)  [especially on the PR]

**Comment by tm-kn** [comment]
Thanks for it! I really appreciate your help.

I can agree on one - the way to reference pages by ID is needed. PR for this is definitely welcome.

The main issue with titles and slugs is that they are not unique... The links will always be ambiguous.  I would suggest we have some sort of smarter resolution for titles and slugs where it's going to use pages that are the closest in the tree first.

**Comment by richtier** [comment]
Ah yes, good point - slug lookup has the same problem as title lookup.

I'll make a PR for the primary key linking over the next few days.

**Comment by richtier** [comment]
I closed the PR due to inactivity.

**Comment by pbspm01** [comment]
Hi, this is a very nice feature, removing the pain of linking the pages. We'd love to have this officially!
