### ISSUE TITLE
Use with wagtail-modeltranslation, page links break

### ISSUE THREAD

**Issue by stuaxo** [torchbox/wagtail-markdown#41]
Hi,
   I've tried using this with wagtail modeltranslation.   I've got a page link, it works to the default language (English) - but the link is broken on the fallback languages.

Cheers
S

**Comment by stuaxo** [comment]
Realised this breaks because the link uses Title ... hrm, maybe I need to implement the version that works with slug :(

**Comment by stuaxo** [comment]
Maybe not - maybe it's breaking because my urls use i18n_patterns  ?

**Comment by zerolab** [comment]
@stuaxo as of https://github.com/torchbox/wagtail-markdown/releases/tag/v0.10.0 we can do inline links using page, document, image (and wagtailmedia) object PKs, so this should hopefully be covered. Using PKs is more solid than title or slug as they both can and will change
