### ISSUE TITLE
SimpleMDE ReferenceError: Can't find variable: simplemdeAttach

### ISSUE THREAD

**Issue by zcho** [torchbox/wagtail-markdown#5]
Wagtail: 1.3.1 version
wagtail-markdown installed with:pip -e git+https://github.com/torchbox/wagtail-markdown.git#egg=wagtail_markdown

Then

``` python
...
from wagtailmarkdown import MarkdownBlock
...
class BlogBodyStreamBlock(StreamBlock):
    intro = RichTextBlock(icon="pilcrow")
     ...
    markdown = MarkdownBlock(icon="code")

class BlogPage(Page):
    body = StreamField(BlogBodyStreamBlock)
    content_panels = Page.content_panels + [
        ...
        StreamFieldPanel('body'),
    ]

```

In admin interface no MDE editor, and got error in JS console:
:beetle: **_"ReferenceError: Can't find variable: simplemdeAttach"**_

**Comment by ftarnell** [comment]
Hello,

Does the HTML generated in the editor include `simplemde.min.js` and `simplemde.attach.js`?

```
<script type="text/javascript" src="/static/wagtailmarkdown/js/simplemde.min.js"></script>
<script type="text/javascript" src="/static/wagtailmarkdown/js/simplemde.attach.js"></script>
```

If not, could you please try the `mediafix` branch instead and see if that works better?  You'll need to change your import to `from wagtailmarkdown.fields import MarkdownBlock`.

Thanks.

**Comment by zcho** [comment]
Hello,

I tried this branch.

Yes included!
```
<script type="text/javascript" src="/static/wagtailadmin/js/blocks/sequence.js"></script>
<script type="text/javascript" src="/static/wagtailadmin/js/blocks/stream.js"></script>
<script type="text/javascript" src="/static/wagtailmarkdown/js/simplemde.min.js"></script>
<script type="text/javascript" src="/static/wagtailmarkdown/js/simplemde.attach.js"></script>
<script type="text/javascript" src="/static/wagtailadmin/js/blocks/struct.js"></script>
<script type="text/javascript" src="/static/wagtailadmin/js/blocks/list.js"></script>
```


But, effect the same.
<img width="1386" alt="screen shot 2016-01-22 at 12 52 47" src="https://cloud.githubusercontent.com/assets/689781/12507520/575063f4-c107-11e5-85ef-747a10eb7953.png">

But in works if i hack admin template
```
/.virtualenvs/wagtail/lib/python3.4/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/home.html
```

by adding js and css in it.

**Comment by tm-kn** [comment]
It should work because of that.
https://github.com/torchbox/wagtail-markdown/blob/0c3f5ef45badedf617fdb85e40ca718d32fe6f9e/setup.py#L35-L39
