### ISSUE TITLE
Customized toolbar based on var

### ISSUE THREAD

**Issue by robslotboom** [torchbox/wagtail-markdown#52]
Some time ago customized the “original version” of wagtail markdown to alter the tool in the toolbar based on a variable.

Due to changes in wagtail markdown these customizations no longer work anymore.

But maybe there is some interest in the code?

Cheers,

Rob

**Comment by zerolab** [comment]
Hey @robslotboom, do share the code. 
You never know who finds it useful and could take it further.

**Comment by zerolab** [comment]
I would create [Gist](https://gist.github.com) and link here. Makes it easier to maintain, even if it is a collection of scattered snippets :)

**Comment by robslotboom** [comment]
> Op 26 sep. 2018, om 15:10 heeft Dan Braghis <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:
> 
> Hey @robslotboom <https://github.com/robslotboom>, do share the code.
> You never know who finds it useful and could take it further.
> 
Hi Dan,

Did some work.
See attachment for an impression.

Cheers,

Robert

**Comment by zerolab** [comment]
@robslotboom I believe #104 takes care that now.
