### ISSUE TITLE
requires Wagtail<2.3 but latest is at 2.4

### ISSUE THREAD

**Issue by henrikq-vipps** [torchbox/wagtail-markdown#53]
see:
https://pypi.org/project/wagtail

**Comment by jhoover4** [comment]
What needs to be done to get this up to 2.4?

**Comment by zerolab** [comment]
You could test it with your own form where you change the requirement, add something along the lines of `e git+https://github.com/jhoover4/wagtail-markdown.git@COMMIT_SHA_HERE#egg=wagtail-markdown` to requirements.txt and check what breaks?

**Comment by jhoover4** [comment]
Sure be happy to help! Know where you are on tests? That would obviously speed things up :)
