### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [torchbox/wagtail-markdown#54]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by kevinhowbrook** [comment]
Apologies, I took over maintenance and wasn't tracking the repo.

**Comment by bashu** [comment]
@kevinhowbrook 👍

**Comment by bashu** [comment]
@kevinhowbrook can I hope to see a minor version on pypi in a near future?

**Comment by kevinhowbrook** [comment]
^ @tm-kn ?
