### ISSUE TITLE
Unable to get quotes to work

### ISSUE THREAD

**Issue by danihodovic** [torchbox/wagtail-markdown#63]
I'm trying to get markdown quotes to work using >, but it's not being rendered by wagtail

> This is a quote

**Comment by zerolab** [comment]
Cannot reproduce. See below when using wagtail-markdown with bakerydemo

![Screenshot 2021-04-19 at 09 24 28](https://user-images.githubusercontent.com/31622/115206017-10d73080-a0f2-11eb-87bd-81adef029f1e.png)
![Screenshot 2021-04-19 at 09 24 39](https://user-images.githubusercontent.com/31622/115206022-116fc700-a0f2-11eb-93e0-79aad42a6589.png)
