### ISSUE TITLE
Customise SimpleMDE options?

### ISSUE THREAD

**Issue by thomas-ricci** [torchbox/wagtail-markdown#64]
Hi all, and thank you Torchbox!

Is it possible to customise the SimpleMDE configuration like [this](https://github.com/sparksuite/simplemde-markdown-editor#configuration)? I would like to hide some icons and disable spell checking.

I can access `/static/wagtailmarkdown/js/simplemde.attach.js` and modify options during the creation of the `new SimpleMDE()` but nothing seems to apply. If I try `console.log('test')` in this file I also can't see the log, so I'm assuming this file isn't what is being read when editing my pages in Wagtail, however the debugger says my browser is pulling this exact file:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/1481725/60415731-4f4ee300-9c1f-11e9-90a4-8b8393fd1cb2.png">

Any help would be greatly appreciated! Thank you.

**Comment by photong** [comment]
I can verify that changing options in simplemde.attach.js works. I turned off the spellchecker by setting "spellChecker: false".

**Comment by jeriox** [comment]
Would love that feature as well as we want to add additional buttons to the SimpleMDE toolbar

**Comment by zerolab** [comment]
Fixed by #104/#105
