### ISSUE TITLE
How to display full-width images?

### ISSUE THREAD

**Issue by danihodovic** [torchbox/wagtail-markdown#65]
Could you provide an example of how to display full-width images in the markdown. It's not obvious when reading the code.

**Comment by adinhodovic** [comment]
You can override the default width by using:
```
<:image:cool_image.png|width=1000>
```
If your image is 700px set the width to 700 and the image will be the full-width original image size. But you can't stretch images, setting it to 800 will be just as big as the original image.

You could set the width to 5000 for all images and it'll stretch to full size for all images (except if some exceed 5000px). Still can't grasp how to use the variable 'full' as it does not override opts['spec'] as width does. https://github.com/torchbox/wagtail-markdown/blob/master/wagtailmarkdown/mdx/linkers/image.py#L45

By default all images are up to 500px large. The height scales automatically as usual with HTML.

**Comment by fernandolins** [comment]
Is there a way to customizing linkers image format?
Nowadays it accepts left, right and full format.

[To RichText we can register custom image format](https://docs.wagtail.io/en/stable/advanced_topics/customisation/page_editing_interface.html#image-formats-in-the-rich-text-editor). Can we do that to Markdown as well?

**Comment by zerolab** [comment]
@danihodovic with https://github.com/torchbox/wagtail-markdown/releases/tag/v0.10.0 you could use the inline image reference `![alt text][image:PK,class=full-width,filter=width-1000)`

**Comment by danihodovic** [comment]
Nice one @zerolab
