### ISSUE TITLE
switch to a maintained fork of SimpleMDE

### ISSUE THREAD

**Issue by alee** [torchbox/wagtail-markdown#72]
simplemde has an [outstanding CVE](https://github.com/advisories/GHSA-wg85-p6j7-gp3w) and doesn't appear to be maintained anymore. Would it be possible to switch to a maintained fork like https://github.com/Ionaru/easy-markdown-editor ?

**Comment by zerolab** [comment]
Thank you for this @alee,

We would certainly welcome a PR for it.

**Comment by StefanUlbrich** [comment]
#76 Should allow to use the maintained editor

**Comment by zerolab** [comment]
Fixed in #76
