### ISSUE TITLE
MarkdownBlock Empty after saving in Wagtail 2.13

### ISSUE THREAD

**Issue by rokondo** [torchbox/wagtail-markdown#79]
After press "Save draft" the content of the MarkdownBlock disappears (also for publishing). When I publish direct in one step it publishes the content, but I cannot edit, because the textarea is blank afterwards.

```python
    body = StreamField([
        ('heading', blocks.CharBlock(form_classname="full title")),
        ('paragraph', blocks.RichTextBlock(required=False)),
        ('image', ImageChooserBlock()),
        ('image_wide', MyWideImage()),
        ('text',MarkdownBlock())],
        blank=True)
# ...
   content_panels = Page.content_panels + [
# ...
        StreamFieldPanel('body'),
# ...
    ]
```

I am new to wagtail and just start the first project, so when I could send something for debug let me know! Migrate I runned..

I am using: python 3.9 + django 3.2.3 + wagtail 2.13 + wagtail-markdown 0.6
(tried also with wagtail-markdown v0.7.0-rc1)

Update: I checked the database and the value is written correctly. So I assume it is a problem with reading the value:
`, {"type": "text", "value": "ds\r\nds\r\nds\r\nds\r\nds\r\nds\r\nds\r\nd\r\nds\r\nds\r\nds", "id": "77faf527-1d4c-45ec-bf42-456a18724590"}]`

**Comment by rokondo** [comment]
Downgraded wagtail to 2.12.4 and now it works. I let issue open because it should work with latest version somewhen?

**Comment by zerolab** [comment]
Hey @rokondo,
Sorry for the delay in response. Wagtail 2.13 changed the client side for StreamField blocks. I suspect that has something to do with that. https://docs.wagtail.io/en/stable/releases/2.13.html#new-client-side-implementation-for-custom-streamfield-blocks

Will try to work on this in the coming days, but any help is most welcome

**Comment by rokondo** [comment]
I would like to help but I am new to wagtail / django and even don't know where the problem exactly occurs because I found no error message (or I cannot find the error messages correctly)

**Comment by jcuotpc** [comment]
I have encountered the same problem.
My environment is: 
python == 3.8.0
Django == 3.2.4
wagtail == 2.13.1
wagtail-markdown == 0.6

**Comment by zerolab** [comment]
Hey @rokondo, @jcuotpc I've opened #81. Could you please test on your builds?

**Comment by zerolab** [comment]
I've release v0.7.0-rc2 - https://pypi.org/project/wagtail-markdown/0.7.0rc2/

**Comment by AndresJaramillo95** [comment]
Just wanted to comment and say thank you for fixing this with the v0.7.0 release.
