### ISSUE TITLE
FontAwesome is a dependency

### ISSUE THREAD

**Issue by rjmoggach** [torchbox/wagtail-markdown#8]
FontAwesome as a dependency needs to be documented or maybe a subset webfont should be created to meet the needs of the UI and put in the static media as appropriate.

**Comment by nimasmi** [comment]
#17 adds a change to include FontAwesome instructions in the README

**Comment by tm-kn** [comment]
Can't we just add https://github.com/alexgleason/wagtailfontawesome as a dependency?

**Comment by zerolab** [comment]
The FontAwesome dependency and manual modes got documented a while back.
Also, https://github.com/torchbox/wagtail-markdown/pull/76#issuecomment-822019503 -- discovered that SimpleMDE (and now EasyMDE) will happily use FontAwesome from the CDN, unless told otherwise
