### ISSUE TITLE
Custom extensions in MarkdownBlock

### ISSUE THREAD

**Issue by rokdd** [torchbox/wagtail-markdown#80]
Sorry for asking more but I am a big fan of markdown and it's system. So I thought it is worth to implement a [icon library](https://github.com/MadLittleMods/markdown-icons) and implementented into the extensions (and this works):

`WAGTAILMARKDOWN_EXTENSIONS = ["toc", "sane_lists",'home.extensions.iconfonts:IconFontsExtension']`

But in the markdown it does not handle the result safe:
![grafik](https://user-images.githubusercontent.com/640866/120545008-63dd1c80-c3ee-11eb-8d35-89c132079f52.png)

As you can see the other markdowns for bold text was working. So do I something wrong? What is the best way to fix..? The MarkdownBlock in a Streamfield so I can not set it safe in the template.

**Comment by zerolab** [comment]
Hey @rokondo,

At the moment the `<i>` tag and the `aria-*` tags are not in the list of allowed [bleach](https://github.com/mozilla/bleach) tags/attributes as per https://github.com/torchbox/wagtail-markdown/blob/main/wagtailmarkdown/utils.py#L39

#59 does provide the means for custom extentions to extend the bleach configuration, but we went with with the #69 for custom extension. Will add to my list to look at.

**Comment by rokondo** [comment]
I guess this should be a good option because I already saw that others also whiched the `sup` tag for example. IMHO there should be also a option for `WAGTAILMARKDOWN_BLEACH_ALLOWED_TAGS` because as I understood else, it does not help to add the attributes..?

**Comment by zerolab** [comment]
True that. Will look at providing a unified setting `WAGTAILMARKDOWN` that would be a dict of the various other settings. Django Rest Framework and others do it similarly. Unless, of course, you happen to have some spare time to submit a PR :D

**Comment by rokondo** [comment]
I mentioned some stuff in the PR directly. Maybe my approach is too easy: https://github.com/torchbox/wagtail-markdown/pull/82

**Comment by zerolab** [comment]
Fixed by #82
