### ISSUE TITLE
Don't sanitise markdown output

### ISSUE THREAD

**Issue by freesteph** [torchbox/wagtail-markdown#83]
I'm trying to import some content that contains both Markdown and HTML.

As far as I know having HTML in Markdown is perfectly valid and should be rendered correctly. However wagtail-markdown always sanitizes it: https://github.com/torchbox/wagtail-markdown/blob/main/wagtailmarkdown/utils.py#L27

Any reason for that? Or a way to turn it off?

Thanks!

**Comment by zerolab** [comment]
The defaults sanitise the markup to that used by default in the editor.
#82 will provide means to extend the allowed tags and more.

**Comment by zerolab** [comment]
[version 0.7.0](https://github.com/torchbox/wagtail-markdown/releases/tag/0.7.0) should allow you to customise what gets sanised and what doesn't. Please give it a try
