### ISSUE TITLE
Lack of detailed document for configuration

### ISSUE THREAD

**Issue by tian-yan** [torchbox/wagtail-markdown#88]
I am installing and configuring wagtail-markdown, in the github page, it reads:
> # settings.py
> 
> WAGTAILMARKDOWN = {
>     "autodownload_fontawesome": False,
>     "allowed_tags": [],  # optional. a list of tags
>     "allowed_styles": [],  # optional. a list of styles
>     "allowed_attributes": {},  # optional. a dict with HTML tag as key and a list of attributes as value
>     "extensions": [],  # optioanl. a list of extensions
>     "extension_configs": {},  # optional. a dictionary with the extension name as key, and its configuration as value
> }

However, I did not find any documents answering below questions:
1) what tags can be put in `"allowed_tags": []` and in what format `"allowed_tags": ["tag#1", "tag#2", "tag#3"]` ?
2) what extensions are supported ?
3) what are default values for all those configuration options, default value for `[]` and `{}` is `blank` ?

**Comment by zerolab** [comment]
I've moved the defaults to https://github.com/torchbox/wagtail-markdown/blob/main/src/wagtailmarkdown/constants.py and linked from the README. I think this is plenty for now
