### ISSUE TITLE
How to populate a portion of post in markdown format into post list

### ISSUE THREAD

**Issue by tian-yan** [torchbox/wagtail-markdown#89]
I am using Wagtail along with wagtail-markdown, and I have a list of posts all in Markdown Format. 
```
### HTML template file,  Post_List.html ###
{% extends 'Base_Layout.html' %}
{% load wagtailcore_tags wagtailroutablepage_tags debugger_tags comments wagtailmarkdown %}

{% block main %}
{% page|pdb %}
    <main>
        {% for post in page.posts %}
   </main>
{% endblock %}

(Pdb++) pp obj.posts[1].body|markdown
*** NameError: name 'markdown' is not defined
(Pdb++) pp type(obj.posts[1].body)
<class 'str'>
(Pdb++) pp obj.posts[1].body[:100]
```
`obj.posts[1].body` is a string in raw markdown format.  

I tried `<p>{{post.body|markdown.getElementsByTagName("P")[0]}}</p>`, but it failed with below error `Could not parse the remainder: '.getElementsByTagName("P")[0]' from 'post.body|markdown.getElementsByTagName("P")[0]'`.

**Q1: In the HTML template of Post List, how can I capture a portion of a specific post in Markdown format, and populate that into the post list webpage?**

**Q2: How can I get the first image from the raw markdown content and populate into the post list html file?**

**Comment by zerolab** [comment]
You are missing `wagtailmarkdown` in your `{% load ... %}` statement.

and you cannot use `markdown.getElementsByTagName("P")[0]}}` in a Django template tag as that is a JavaScript construct

**Comment by tian-yan** [comment]
thanks for pointing out. I already updated `wagtailmarkdown` into the `{% load ... %}` in this post, it was added in as well in my source code. 
Do we have any solution if I can not use `getElementsByTagName` please ?

**Comment by zerolab** [comment]
@tian-yan you should move that sort of logic to Python and probably use something like [BeautifulSoup](https://pypi.org/project/beautifulsoup4/) to do the processing that you need. Or write a [custom template tag](https://docs.djangoproject.com/en/3.2/howto/custom-template-tags/) that takes your raw markdown, renders it and then pulls out whatever it needs. See waht the `|markdown` filter does - https://github.com/torchbox/wagtail-markdown/blob/main/wagtailmarkdown/templatetags/wagtailmarkdown.py#L20

Will close this issue as it is not a package-related issue per se.

I suggest asking support questions in the Wagtail Slack, the #support channel. See https://github.com/wagtail/wagtail/wiki/Slack for more details
