### ISSUE TITLE
HTML renderred by wagtail-markdown is not recoginzed as HTML contents by browser

### ISSUE THREAD

**Issue by tian-yan** [torchbox/wagtail-markdown#91]
I am using Wagtail + Wagtail_markdown to support editing blog post using markdown.
In order to save the CPU for rendering markdown to HTML every time when blog post is viewed by internet end users, I will save both **Markdown** (for editing) and **HTML** (for viewing by end users) version in DB. 
>Based in the **[wagtail_markdown source code of template filter](https://github.com/torchbox/wagtail-markdown/blob/92cbadf98545654955471a213dd13930ba417afe/wagtailmarkdown/templatetags/wagtailmarkdown.py#L18)** as below.
>```
>@register.filter(name="markdown")
>def markdown(value):
>    return render_markdown(value)
>```
>I override the default **`page.save()`**  in **`App/models.py`**.

#### in App/models.py
```
from wagtailmarkdown.utils import render_markdown

class PostDetail(Page):
    template = "Post_Detail.html"
    
    body = MarkdownField()
    html_body = models.TextField(editable=False, default="Empty")

    def save(self, html_body=None, *args, **kwargs):
        self.html_body = render_markdown(self.body)
        return super().save(*args, **kwargs)
```

#### in template file: Post_Detail.html
```
{% load wagtailmarkdown %}

<div class="markdown">
      {{ page.html_body }}   ## It was working perfectly if I replaced this row with '{{ page.body | markdown  }}'
</div>
```

After inspect elements in browser, I can see HTML content within **`<div class="markdown">`**. **However, those HTML contents seems not understood by browser at all, because they are displayed as raw text string along with HTML tags.**  On the webpage, you will see paragraph contents as below:
```
<p>this is the first paragraph of this blog post</p>
<p><img alt="pic_name" src="http://abc.com/ZIP.jpeg"></p>
<p>this is the second paragraph of this blog post</p>
```
and they are not styled according to my CSS file either. 

**Anything I missed out ??**

**Comment by tian-yan** [comment]
I figured out myself, it is a very basic knowledge point (HTML Escaping) for Django actually.  Apply **`safe`** Django template filter solves the problem.
#### in template file: Post_Detail.html
```
{% load wagtailmarkdown %}
<div class="markdown">
      {{ page.html_body|safe }}  
</div>
```
However, my original intention is minimize the workload of  web server every time when the page is loaded by viewers. So, I am wondering whether I should get rid of this **`safe`** or any template filter to further reduce the workload ? If yes, then how please ? I did not see possibility for saving `{{ page.html_body|safe }} ` in database.

**Comment by zerolab** [comment]
`|safe` is a tempalte tag that uses [`mark_safe`](https://github.com/django/django/blob/4a43335d300da942602fbf216cd0a53b60827ab4/django/utils/safestring.py#L50) to mark the string as "safe" to be displayed unescaped in the template.

This is what [`render_markdown`](https://github.com/torchbox/wagtail-markdown/blob/92cbadf98545654955471a213dd13930ba417afe/wagtailmarkdown/utils.py#L29) does too. However the fact that you mark it as safe then store it in the database means you're saving the processed HTML to the database, which by all intents and purposes is raw HTML which Django correctly encodes when output in the template, so using `|safe` is the way to go.
