### ISSUE TITLE
`allowed_attributes` settings wipes out default `allowed_attributes` unexpectedly.

### ISSUE THREAD

**Issue by tian-yan** [torchbox/wagtail-markdown#92]
by default, `allowed_attributes` for `<img>` are `["src", "alt"]`.
When I configure my `settings.py` as below, 
```
WAGTAILMARKDOWN = {
    "allowed_attributes": {"img": ["title"] 
                            },  
}
```
Based on the source code **[wagtailmarkdown/utils.py](https://github.com/torchbox/wagtail-markdown/blob/92cbadf98545654955471a213dd13930ba417afe/wagtailmarkdown/utils.py#L146)**
```
if "allowed_attributes" in settings.WAGTAILMARKDOWN:
            bleach_kwargs["attributes"] = {
                **bleach_kwargs["attributes"],
                **settings.WAGTAILMARKDOWN["allowed_attributes"],
            }
```
Newly added `allowed_attributes` should be added on top of default `allowed_attributes`. However, based on my testing here, default `allowed_attributes` are wiped out and the resulted `<img>` only has attribute`title=" "` now.
```
'<p><img title=" "></p>\n'
'<p><img title=" "></p>\n'
```

problem can be solved by including default `allowed_attributes` in the `settings.py` configurations.
```
WAGTAILMARKDOWN = {
    "allowed_attributes": {"img": ["title", "src", "alt"] 
                            },  
}
```
It is a minor issue, but since I experienced it, just share with the team.

**Comment by zerolab** [comment]
#108 aims to address this, and provide 2 additional settings to control how the `allowed_*`, as well as the `extension*` settings behave (default: extend. but can be replaced)
