### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtail-markdown#98]
The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

There’s only one thing – apparently this package relies on Wagtail’s tabs implementation, which has been removed. Here are the results of our code search:

```
torchbox/wagtail-markdown/wagtailmarkdown/static/wagtailmarkdown/js/easymde.attach.js
43:$(document).on('shown.bs.tab', function(e) {
```

This will likely need investigation and rework. From what I understand of this code, this type of customisation still remains unsupported – if we need to make changes in Wagtail so there is an official API for this, please request this via GitHub issues.

**Comment by zerolab** [comment]
This bit trigger the editor render when included in the non-default tab.
I think it is a valid use case and we probably want an official API for that
